### ISSUE TITLE
Migrate to YunoHost Apps org

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/arn_messager_ynh#1]
I may start working on this next tuesday, could you transfer your draft to the yunohost apps org so we publish it soon ? 
And maybe rename it arn_messager_ynh

Or we could also find a cool name for the interoperable chat system it enables.

**Comment by Thatoo** [comment]
I really didn't do much, but yes, I will transfer it (as soon as I found how) with the name arn_messager_ynh

**Comment by Thatoo** [comment]
Unfortunately https://github.com/yunoHost-Apps/arn_messager_ynh does already exist so I can't "transfert" ownership.
